# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import short_pb2 as short__pb2


class ShortStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Short = channel.unary_unary(
                '/Short/Short',
                request_serializer=short__pb2.shortUrl.SerializeToString,
                response_deserializer=short__pb2.shortUrl.FromString,
                )


class ShortServicer(object):
    """Missing associated documentation comment in .proto file."""

    def Short(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ShortServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Short': grpc.unary_unary_rpc_method_handler(
                    servicer.Short,
                    request_deserializer=short__pb2.shortUrl.FromString,
                    response_serializer=short__pb2.shortUrl.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'Short', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class Short(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Short(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/Short/Short',
            short__pb2.shortUrl.SerializeToString,
            short__pb2.shortUrl.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
