# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: short.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='short.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x0bshort.proto\"\x17\n\x08shortUrl\x12\x0b\n\x03url\x18\x01 \x01(\t2(\n\x05Short\x12\x1f\n\x05Short\x12\t.shortUrl\x1a\t.shortUrl\"\x00\x62\x06proto3'
)




_SHORTURL = _descriptor.Descriptor(
  name='shortUrl',
  full_name='shortUrl',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='url', full_name='shortUrl.url', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=15,
  serialized_end=38,
)

DESCRIPTOR.message_types_by_name['shortUrl'] = _SHORTURL
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

shortUrl = _reflection.GeneratedProtocolMessageType('shortUrl', (_message.Message,), {
  'DESCRIPTOR' : _SHORTURL,
  '__module__' : 'short_pb2'
  # @@protoc_insertion_point(class_scope:shortUrl)
  })
_sym_db.RegisterMessage(shortUrl)



_SHORT = _descriptor.ServiceDescriptor(
  name='Short',
  full_name='Short',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=40,
  serialized_end=80,
  methods=[
  _descriptor.MethodDescriptor(
    name='Short',
    full_name='Short.Short',
    index=0,
    containing_service=None,
    input_type=_SHORTURL,
    output_type=_SHORTURL,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_SHORT)

DESCRIPTOR.services_by_name['Short'] = _SHORT

# @@protoc_insertion_point(module_scope)
